### ISSUE TITLE
用在adapter中会出现重复多个圆点

### ISSUE THREAD

**Issue by solochen** [why168/LoopViewPagerLayout#1]
用在adapter中，LoopViewPager在滑出可视区域后再次滑回来时会重复创建圆点，有没有办法解决？ 因为在代码里面是在自定义RelativeLayout用了addView(animIndicator);  滑动的时候RelativeLayout在adapter缓存里不会释放，而addView会在每次滑出可视区域都执行一次。希望博主早点解决！

**Comment by why168** [comment]
你是不是放在fragment里面使用的呢？initData()初始化的地方是不是重复了？ 生命周期打印Log看下呢？

**Comment by why168** [comment]
LoopViewPager 的 setLoopData你是不是初始化多次了？

**Comment by why168** [comment]
我这边改了下源码，在setLoopData里面做了判断，如初始化多次,清空图片和小红点。谢谢你哦～！

**Comment by solochen** [comment]
恩，在adapter里面走onBindViewHolder 是会初始化多次setLoopData我没有去判断！但这里可能会动态的去设置page的数量，所以应该会多次调用setLoopData避免不了。

**Comment by solochen** [comment]
感谢及时回复及时修复！大爱！！！

**Comment by solochen** [comment]
多次初始化后红点会莫名的消失了，看代码是removeView后再addView的，帮忙看下！

**Comment by why168** [comment]
2.0版本更新了，不妨试试。gradle直接引用。
