### ISSUE TITLE
Maven无法依赖

### ISSUE THREAD

**Issue by LZKDreamer** [why168/LoopViewPagerLayout#10]
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.why168:LoopViewPagerLayout:2.1.8.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/why168/LoopViewPagerLayout/2.1.8/LoopViewPagerLayout-2.1.8.pom
       - https://jcenter.bintray.com/com/github/why168/LoopViewPagerLayout/2.1.8/LoopViewPagerLayout-2.1.8.pom
       - https://jitpack.io/com/github/why168/LoopViewPagerLayout/2.1.8/LoopViewPagerLayout-2.1.8.pom
     Required by:
         project :app

**Comment by why168** [comment]
我用的这个仓库：https://jitpack.io/com/github/why168/LoopViewPagerLayout/2.1.8/LoopViewPagerLayout-2.1.8.pom
